export const ROUTES_NAME = {
  "HOME": "/",
  "BACKOFFICE_PREFIX": "/backoffice",
  "LOGIN": "/login",
  "CONFIRM_LOGIN": "/confirm-login",
  "DASHBOARD": "/backoffice/dashboard",
  "GAS_STATIONS": "/backoffice/gas-stations",
  "CREATE_GAS_STATION": "/backoffice/gas-stations/create",
  "WEBSITE": "/backoffice/website",
  "RESOURCES": "/backoffice/resources",
  "CREATE_RESOURCE": "/backoffice/resources/create",
  "EDIT_RESOURCE": "/backoffice/resources/edit/:id",
  "USERS": "/backoffice/users",
  "PROFILE": "/backoffice/profile",
} as const;